
#---------------------------------------------------------------------
#  GitHub Action Basics
#  
#---------------------------------------------------------------------
name: My-GitHubActions-Basics
env:
  MY_APPLICATION_NAME    : "My_Flask"
  MY_DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"

on: 
  push:
    branches: 
      - main

jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in First Job
      run : echo "Hello World from First job"
    
    - name: Execure few commands
      run : |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Appication name: ${{ env.MY_APPLICATION_NAME }}"
    
    - name: List current folder
      run : ls -la
   
    - name: Git clone my repo
      uses: actions/checkout@v1   
  
    - name: List current folder
      run : ls -la
  
  my_second_job:
    runs-on: ubuntu-latest
    needs: [my_first_job]
    env:
      VAR1 : "This is Job Level Variable-1"
      VAR2 : "This is Job Level Variable-2"
    
    steps:
    - name: Print Hello Message in Second Job
      run : echo "Hello World from Second job"
      
    

